blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability (Private)
    url: https://github.com/ChrisKrt/c7n.Bookshelf/security/advisories/new
    about: Report a serious security vulnerability privately
